// ! MAIN SECTION
const hamburger = document.querySelector("#hamburger");
const navMenu = document.querySelector("#nav-menu");
if (window.innerWidth >= 900) {
  navMenu.classList.add("nav-menu");
}
window.addEventListener("resize", function () {
  if (window.innerWidth <= 900) {
    document.querySelector(".logo").innerHTML = "Fairuz";
  }
});
hamburger.addEventListener("click", function () {
  hamburger.classList.toggle("hamburgeractive");

  if (navMenu.className == "nav-menu") {
    navMenu.classList.remove("nav-menu");
    navMenu.classList.add("hidden");
  } else {
    navMenu.classList.remove("hidden");
    navMenu.classList.add("nav-menu");
  }
});

// ! PAGE MENU SECTION
window.onscroll = function () {
  const header = document.querySelector("header");
  const fixedNav = header.offsetTop;
  if (window.pageYOffset > fixedNav) {
    header.classList.add("");
  }
};
const data = [
  { title: "Ayam Kecap", link: "31723032.html", description: "Bahan:- 300 gram ayam potong- 2 siung bawang putih- 1 ruas jahe- 200 ml air- 5 buah cabai rawit- 2 butir bawang merah- merica bubuk secukupnya- 2 sendok makan kecap manis- minyak goreng secukupnya- 1 sendok teh gula pasir- garam secukupnyaCara memasak:a. Goreng ayam setengah matang, tiriskan.b. Tumis bawang merah dan bawang putih, tambahkan jahe memar, irisan cabai hingga harum.c. Beri garam dan merica bubuk, lalu tuang air.d. Setelah mendidih, masukkan ayam. Tambahkan kecap dan gula pasir secukupnya.e. Masak sampai ayam matang dan kuah menyusut hingga separuhnya." },
  { title: "Ayam Goreng Mentega", link: "312390182.html", description: "Bahan:- 4 siung bawang putih- 1 kg ayam (potong sesuai selera)- 3 cm kunyit (haluskan)- kaldu ayam bubuk (secukupnya)- ketumbar bubuk (secukupnya)- garam (secukupnya)Bumbu saus mentega:- mentega (secukupnya)- 4 sdm kecap manis- 1 sdm saus tiram- 1 sdt tepung maizena (larutkan ke 1 sdm air)- 4 siung bawang putih (cincang halus)- 1 batang daun bawang (cincang kasar)- 1 buah bawang bombay (iris tipis)- 1 sdm kecap asin- merica bubuk (secukupnya)- garam (secukupnya)- 2 buah cabai merah besar (buang isi, iris serong)- 150 ml airCara memasak:a. Rebus ayam bersama bumbu sampai matang, tunggu sampai asat. Lalu goreng ayam sampai matang. Tiriskan.b. Buat saus mentega, lelehkan mentega 2 sdm.c. Tumis bawang putih dan bawang bombay. Tambahkan kecap manis, kecap asin, saus tiram, merica bubuk, tepung maizena, garam, daun bawang, dan cabai merah. Aduk rata. Tuang air, aduk dan masak hingga mendidih.d. Masukkan ayam goreng, aduk rata." },
  { title: "Ayam Goreng Bawang Putih Pedas Manis", link: "31029181.html", description: "Bahan:- 300 gram dada ayam, potong-potong- 2 sdm tepung maizena- 1 butir telur- 1 sdm tepung terigu- 1 sdt garamBumbu pedas manis:- 6 siung bawang putih, geprak, tak perlu dibuang kulitnya- 4 buah cabai merah kering, haluskan beberapa- 1 sdm madu- 2 siung bawang merah, haluskan- 2 sdm gula pasir- 1 sdm margarinCara memasak:a. Campur semua tepung, garam, dan telur. Rendam ayam dan biarkan selama 30 menit.b. Goreng ayam hingga kecokelatan, tiriskan.c. Tumis bawang putih sampai kering dan matang. Masukkan margarin, tumis bawang merah hingga harum. Masukkan gula pasir, cabai kering dan madu.d. Masukkan ayam goreng dan aduk rata dengan bumbu." },
  { title: "Ayam Teriyaki", link: "31625412.html", description: "Bahan:- 300 gram daging ayam, potong-potong- 1 buah jeruk nipis- 1 buah brokoli, potong-potongBumbu:- 2 siung bawang putih, cincang- 1/2 sdt merica bubuk- garam dan gula secukupnya- 1/2 siung bawang bombay- 2 sdm saus tiram- 2 sdm saus teriyaki- 1 sdm tepung maizenaCara memasak:a. Campur air jeruk nipis dan ayam, diamkan 15 menit, bilas bersih. Sisihkan.b. Rebus brokoli setengah matang, tiriskan.c. Tumis bawang putih dan bawang bombay. Masukkan ayam dan tumis hingga berubah warna.d. Tuang saus tiram, saus teriyaki, dan beri merica bubuk. Aduk rata. Masukkan brokoli dan aduk rata.e. Tuang tepung maizena yang sudah dicampur air secukupnya. Aduk rata hingga mengental. Beri gula dan garam secukupnya." },
  { title: "Ayam Bakar Bumbu Padang", link: "31398342.html", description: "Bahan:- 4 potong paha ayam- 1 lembar daun kunyit- 150 ml santan kelapa- 1 buah jeruk nipis, ambil air perasannya- 3 lembar daun salam- minyak goreng dan kaldu bubuk secukupnya- 4 lembar daun jerukBumbu halus:- 4 siung bawang putih- 1 cm kunyit- 2 batang serai, ambil bagian putihnya- 8 siung bawang merah- 1 1/2 sdt ketumbar- 1 ruas jahe- garam secukupnya- 2 ruas lengkuas- 4 buah cabai merah- 3 butir kemiriCara memasak:a. Cuci bersih daging ayam, kucuri dengan air perasan jeruk nipis, diamkan 20 menit, lalu bilas hingga bersih.b. Tumis bumbu halus, tambahkan kunyit, daun salam, dan daun jeruk. Tuang kaldu bubuk dan santan. Aduk rata.c. Masukkan ayam, masak hingga bumbu meresep dan daging empuk.d. Panggang ayam ke atas teflon atau pemanggang." },
  { title: "Ayam Bakar Madu", link: "31917238.html", description: "Bahan:- 6 potong sayap ayam- 4 sdm minyak goreng- 4 sdm maduBumbu halus:- 6 siung bawang merah- 1/2 sdt lada bubuk- 1 sdt garam- 3 siung bawang putih- 1/2 sdt ketumbar- 1 sdm kecap asin- 1 ruas jahe- air secukupnya- 1 sdm kecap manisCara memasak:a. Masak ungkep ayam dengan bumbu haluskan sampai matang. Angkat dan biarkan dingin.b. Oleskan madu dan minyak goreng pada ayam.c. Bakar ayam sampai berwarna cokelat kehitaman di bagian luar." },
  { title: "Serundeng Ayam", link: "315238712.html", description: "Bahan:- 1 kg daging ayam, potong jadi 10 bagian- 1 lembar daun salam- 1 cm lengkuas- 1 batang serai, memarkan- 2 lembar daun jeruk- kelapa parut, dari satu buah kelapaBumbu halus:- 6 siung bawang putih- 1 ruas kunyit- 3 siung bawang merah- 3 butir kemiri- 1 ruas jahe- 2 sdt ketumbar- 1 sdt gula jawa- 1 sdt garam- 500 ml air- penyedap masakan secukupnyaCara memasak:a. Cuci bersih ayam lalu rebus hingga matang, tiriskan.b. Tumis bumbu halus, masukkan batang serai, daun salam, daun jeruk dan lengkuas, aduk rata. Tuang air masak sampai mendidih.c. Masukkan daging ayam lalu ungkep bersama bumbu hingga air menyusut.d. Masukkan parutan kelapa. Masak hingga air asat. Angkat.e. Goreng ayam bersama serundeng hingga matang dan berwarna kecokelatan." },
  { title: "Ayam Woku", link: "400231232.html", description: "Bahan:- 1 kg daging ayam- gula dan kaldu bubuk secukupnya- air perasan jeruk nipis dan garam secukupnyaBahan halus:- 5 siung bawang putih- 3 ruas jahe- 12 siung bawang merah- 4 butir kemiri- 8 buah cabai rawit- 1 ruas kunyit- 4 buah cabai merahBumbu iris:2 batang serai2 buah tomat1 lembar daun kunyit5 lembar daun jeruk1 batang daun bawangdaun kemangi secukupnyaCara memasak:a. Beri garam dan air perasan jeruk nipis pada ayam, diamkan beberapa saat.b. Tumis bumbu halus dan daun jeruk. Tambahkan garam, gula, dan kaldu bubuk secukupnya.c. Masukkan ayam, tuang air sedikit demi sedikit dan bumbu iris. Masak sampai air menyusut.d. Beri kemangi. Aduk.0" },
  { title: "Ayam Geprek", link: "31029181.html", description: "Bahan:- 1/2 ekor daging ayam- 8 butir bawang merah- 1/2 buah jeruk nipis- 100 gram cabe ijo keriting- minyak kelapa- 1 siung bawang putih- garam dan gulaBumbu ungkep ayam:- 3 siung bawang putih- 2 cm kunyit- 2 cm jahe- 1/2 sdt ketumbar bubuk- garamCara memasak:a. Cuci bersih ayam, ungkep bersama bumbu selama 1 jam. Lalu goreng hingga kecokelatan.b. Ulek kasar cabe ijo, bawang merah, dan bawang putih. Kucuri sedikit air perasan jeruk nipis. Tumis sebentar dengan minyak kelapa. Beri gula dan garam secukupnya.c. Taruh sambal cabai hijau di atas ayam, geprek ayam goreng." },
  { title: "Tumis Ayam Kemangi Kacang Panjang", link: "31723032.html", description: "Bahan:- 2 buah dada ayam, potong-potong tipis- 3 batang kacang panjang, potong-potong- 1 sdt kecap manis- 3 siung bawang putih- 1 siung bawang merah- gula dan merica bubuk secukupnya- 2 buah cabai merah, iris tipis- 1 buah jeruk nipis- 1 genggam daun kemangi- 1 sdm kecap asin- 1 sdm saus tiramCara memasak:a. Lumuri ayam dengan jeruk nipis, diamkan 10 menit. Bilas bersih.b. Tumis bawang putih dan bawang merah cincang, masukkan ayam lalu tumis lagi sampai matang. Tambahkan cabai, kacang panjang, masak hingga agak layu.c. Masukkan semua bumbu dan kemangi. Aduk rata." },
  { title: "Ayam Goreng Tepung Renyah", link: "312390182.html", description: "Bahan:- 1 ekor ayam, potong-potong- 1 sdm tepung maizena- 1 butir telur- 5 siung bawang putih, haluskan- 5 sdm tepung terigu- garam, merica, dan penyedap rasa secukupnyaCara memasak:a. Lumuri daging ayam dengan bawang putih, merica, penyedap rasa, dan garam. Dinginkan di dalam lemari es selama 1 jam.b. Masukkan tepung terigu dan maizena ke dalam wadah. Tuang kaldu bubuk ayam dan beri merica secukupnya.c. Kocok telur, beri sedikit garam. Masukkan ayam. Lalu lumuri dengan tepung, balut sambil dicubit-cubit agar krispi.d. Goreng ayam di dalam minyak panas, tiriskan." },
  { title: "Ayam Taliwang", link: "31029181.html", description: "Bahan:- 1 ekor ayam potong, potong jadi empat bagian- 1 sdm gula merah, sisir- 2 sdm kecap manis- garam dan air secukupnyaBumbu:- 7 siung bawang putih- 10 buah cabai rawit- 15 buah bawang merah- 10 buah cabai keriting- 1 buah tomat- 2 ruas kencur- 1 sdt rebon atau 1 cm terasiCara memasak:a. Tumis bumbu halus. Masukkan ayam masak sambil diaduk hingga ayam berubah warna.b. Tuang air secukupnya. Masukkan gula dan garam. Masak hingga ayam empuk dan air habis.c. Panggang ayam bersama bumbu hingga kering dan terpanggang sempurna." },
  { title: "Ayam Gulai", link: "31723032.html", description: "Bahan:- 1/2 ekor ayam- 2 lembar daun salam- 200 ml santan encer- air matang secukupnya- 1 buah jeruk nipis- garam dan kaldu bubuk secukupnya- 1 batang serai geprek- 2 lembar daun jeruk- 200 ml santan kentalBumbu halus:- 6 siung bawang merah- 3 butir kemiri sangrai- 3 cm kunyit- 1 sdm ketumbar- 3 siung Bawang Putih- 5 buah cabai rawit- 4 cm lengkuas muda- 3 cm jahe- 1 sdt lada bubuk- 10 cabai merah keritingCara memasak:a. Cuci bersih ayam lalu kucuri jeruk nipis, diamkan 10 menit.b Tumis bumbu halus, masukkan daun salam, daun jeruk, dan sereh, aduk.c. Masukkan ayam, masak sampai berubah warna. Beri garam dan kaldu. Aduk rata.d. Tuang santan encer dan air, masak sampai ayam empuk.e. Tunggu sampai kuah menyusut dan ayam empu. Tuang santan kental, masak sambil terus diaduk sampai santan mendidih." },
  { title: "Ayam Goreng Bacem", link: "312390182.html", description: "Bahan:- 8 potong ayam- 1 sdm gula pasir- 5 lembar daun salam- 2 ruas lengkuas- 1 liter air kelapa- 70 gram gula merah- 1 sdm asam jawa, larutkan dengan 100 ml air panas- 5 sdm kecap manis- 1 genggam kulit bawang merah- garam- minyak gorengBumbu halus:- 1 1/2 sdt ketumbar- 3 siung bawang putih- 7 siung bawang merahCara memasak:a. Masukkan air kelapa ke dalam panci. Beri gula merah iris, gula pasir, tuang larutan air asam jawa, kecap manis, kulit bawang merah, dan garam, aduk rata.b. Masukkan ayam. Masak hingga air mengering. Angkat ayam dan tiriskan.c. Goreng ayam hingga berubah warna cokelat keemasan." },
  { title: "Ayam Coca Cola", link: "31029181.html", description: "Bahan:- 250 gram daging ayam- 250 ml coca cola- garam, kaldu bubuk, gula, dan minyak sayur secukupnya- 2 buah bawang putih, cincang halus- 1/2 bawang bombai, iris tipis- 3 sdm kecap manisCara memasak:a. Tumis bawang putih dan separuh bawang bombai. Masukkan ayam, aduk hingga ayam mulai pucat. Masukkan coca cola, biarkan hingga mendidih.b. Tuang kecap manis, beri garam, gula, kaldu bubuk, aduk rata. Masak hingga kuah menyusut.c. tambahkan sisa bawang bombai, aduk rata. Angkat dan sajikan." },
  { title: "Ayam Lodho", link: "31723032.html", description: "Bahan:- 1 kg ayam dipotong 12, bersihkan- 1 ruas lengkuas, geprek- 3 lembar daun salam- 2 buah jeruk nipis- 3 lembar daun jeruk- 10 cabai rawit merah- 3 batang serai, geprek- 500 ml santan kental- 1 sdt jintan bubuk- garam, gula, minyakBumbu halus:- 15 siung bawang merah- 1 ruas jari kunyit- 2 ruas kencur- 7 siung bawang putih- 4 buah cabai merah keriting- 1 sdm ketumbar- 5 butir kemiri, sangrai- 1 ruas jahe- 1 sdt lada putih- airCara memasak:a. Kucuri ayam dengan perasan air jeruk nipis, garam, lada, dan sedikit minyak. Aduk rata.b. Panggang ayam hingga berubah warna kecoklatan. Angkat.c. Tumis daun salam, daun jeruk, serai dan lengkuas.d. Masukkan bumbu halus dan cabai rawit merah. Tumis lagi hingga harum.e. Tuang jintan bubuk dan santan. Aduk sebentar. Masukkan ayam, aduk rata. Masak sebentar dan aduk rata.f. Beri garam dan gula. Masak hingga air sedikit menguap." },
  { title: "Semur Ayam", link: "31723032.html", description: "Bahan:- 1 ekor ayam (potong jadi 12 bagian)- 1 sdt pala bubuk- 1 sdm garam- 4 butir kemiri yang disangrai- 300 gram kentang, potong-potong- 4 buah tahu kotak kecil, potong miring jadi 2 bagian- 6 butir bawang merah- 3 siung bawang putih- 3 cm kayu manis- 1/2 sdt ketumbar yang disangrai- 1 cm jahe- 2 sdm minyak goreng- 1/2 sdt air perasan jeruk nipis- 1/2 sdm garam- 1/2 sdt merica bubuk- 1000 ml air- 2 lembar daun salam- 6 buah cengkeh- 2 buah tomat yang dipotong-potong- 150 ml kecap manisCara memasak:a. Cuci bersih daging ayam. Kemudian lumuri dengan air jeruk nipis dan garam. Diamkan selama 15 menit. Goreng ayam.b. Tumis bawang merah, bawang putih, kemiri, jahe, dan pala yang sudah dihaluskan. Tambahkan daun salam, cengkeh, serta kayu manis. Masukkan potongan tomat, aduk sampai rata dan matang.c. Masukkan daging ayam, aduk sampai bumbu meresap.d. Masukkan potongan kentang dan tahu. Aduk rata lagi.e. Tambahkan 150 ml kecap manis, garam, serta merica bubuk. Aduk.f. Tuangkan air, masak hingga daging empuk dan kuahnya sedikit mengental." },
  { title: "Ayam Goreng Balado", link: "312390182.html", description: "Bahan:- 500 gram daging ayam potong, cuci bersih-1 buah jeruk nipisBumbu halus:- 4 siung bawang putih- 1 sdt ketumbar- 4 siung bawang merah- 1 sdt garam- 1 cm jahe- 1 ruas kunyitBumbu balado halus:- 3 buah cabai merah- 10 buah cabai rawit merah- 3 cabai keriting- 1 sdm gula merah, sisir- 2 siung bawang putih- 1 sdm gula pasir- minyak secukupnya- 1 sdt garamCara memasak:a. Kucuri ayam dengan jeruk, diamkan selama 10 menit. Bilas hingga bersih.b. Ungkep ayam dengan bumbu ungkep yang sudah dihaluskan. Tuang air secukupnya lalu masak hingga matang.c. Goreng ayam sampai kering kecokelatan, tiriskan.d. Tumis bumbu balado. Masukkan ayam goreng. Aduk rata." },
  { title: "Ayam Goreng Lengkuas", link: "31723032.html", description: "Bahan:- 1 kg ayam, cuci bersih dan potong sesuai selera- 4 lembar daun jeruk- 100 gr lengkuas, parut- 1 ruas kunyit, parut- 1 ruas ibu jari jahe, parut- 1 sdt garam- 1 sdt kaldu jamur rasa ayam (opsional)- 300 ml airBumbu halus:- 1 sdm ketumbar bubuk- 9 siung bawang putih, haluskanCara membuat:1. Masukkan ayam dan semua bumbu lainnya, tambahkan air hingga ayam terendam. Aduk rata.2. Biarkan air menyusut. Cek rasa, matikan api.3. Panaskan minyak yang banyak di dalam wajan, goreng ayam hingga matang. Angkat, kemudian lanjutkan menggoreng bumbu lengkuasnya. Jangan menggoreng ayam dan bumbu secara bersamaan karena bumbu akan lebih mudah gosong.4. Sajikan." },
  { title: "Ayam Goreng Ketumbar", link: "312390182.html", description: "Bahan:- 1 kg ayam, potong-potongBumbu:- 7 siung bawang putih, parut- 4 sdm ketumbar bubuk- 4 sdm gula merah- 1/2 buah jeruk nipis- 2 sdm kecap asin- 1 sdm garam- 1 sdm tepung saguCara membuat:1. Tambahkan ayam dengan perasan jeruk nipis, kecap asin, bawang putih, gula merah, ketumbar bubuk, garam, dan tepung sagu. Aduk rata. Marinasi lalu simpan di kulkas pada bagian chiller atas selama 1 malam.2. Goreng di minyak yang telah dipanaskan dengan api kecil. Goreng sampai ayam matang, angkat dan sajikan." },
  { title: "Krengsengan Ayam", link: "31723032.html", description: "Bahan:- 500 gr ayam, potong kecil dan kucuri jeruk nipis, bumbui garam dan lada lalu goreng, sisihkan- 1/2 bawang bombay, rajangBumbu cincang:- 4 siung bawang putih- 6 siung bawang merah- 1/2 buah bawang bombay- 3 cabai merah- 15 cabai rawitBumbu lain:- 1 sdt kecap asin- 1 sdm saus tiram- 3-4 sdm kecap manis- Gula, garam, merica, dan kaldu bubukCara membuat:1. Tumis bumbu cincang hingga tanak, beri sedikit air.2. Masukkan ayam, bumbui dengan saus tiram, kecap asin, kecap manis, gula, garam, merica, dan kaldu bubuk.3. Kecilkan api, saat kuah mulai asat, masukkan rajangan bawang bombay, masak sebentar lalu angkat dan sajikan dengan taburan bawang goreng." },
  { title: "Ayam Pindang Serani", link: "31723032.html", description: "Bahan:- 1 kg ayam- 6 buah belimbing wuluh atau 3 tomat hijau, potong-potong- 1 buah tomat merah, potong-potong- 3 lembar daun salam- 3 lembar daun jeruk- 1 ruas lengkuas- 1 batang serai- 7 siung bawang merah, iris- 5 siung bawang putih, iris- 6 buah cabai rawit merah utuh- 1 ruas jahe, bakar dan iris- 1 ruas kunyit, bakar dan iris- Gula, garam, dan kaldu bubuk secukupnyaCara membuat:1. Rebus ayam sekali mendidih, buang air ganti dengan yang baru. Rebus lagi, masukkan daun salam, daun jeruk, lengkuas, dan serai.2. Di wajan lain, tumis bawang merah, bawang putih, jahe, dan kunyit sampai matang, kemudian masukkan ke rebusan ayam.3. Masukkan tomat hijau atau belimbing wuluh, beri gula, garam, dan kaldu bubuk, masak sampai matang dan meresap hingga ayam empuk dengan api sedang.4. Masukkan tomat iris dan cabai utuhan, aduk-aduk rata.5. Siap disajikan." },
  { title: "Nugget Ayam", link: "312390182.html", description: "Bahan:- 500 gr fillet ayam, potong kecil- 2 butir telur- 2 sdm sagu atau tapioka- 5 siung bawang putih parut- 1 sdt lada bubuk- 50 gr keju parut- 1/2 sdt garam- 1/2 sdt gula- 1 sdm kaldu jamurBahan celup:- 50 gr terigu- 75 ml air- GaramBahan baluran:- Tepung roti secukupnyaCara membuat:1. Blender ayam dan telur hingga lembut, lalu campur semua bahan, tuang di loyang diameter 16x16, alasi plastik dulu sebelumnya lalu kukus selama 30 menit dengan api sedang cenderung kecil hingga matang, biarkan dingin.2. Potong-potong nugget, masukkan ke adonan basah lalu gulingkan di tepung roti, simpan di freezer. Siap digoreng." },
  { title: "Ayam Suwir Kemangi", link: "31029181.html", description: "Bahan:- 400 gr daging ayam, rebus dan suwirBumbu halus:- 9 siung bawang merah- 5 siung bawang putih- 9 cabai rawit- 1 ruas kecil jahe- 1 ruas kecil kunyit- 1/2 sdt terasiBumbu cemplung:- 1 batang serai, geprek- 3 lembar daun jeruk- 1 bungkus santan instan- 1 sdt saus tiram (opsional)- 1 genggam daun kemangi- Gula, garam, dan kaldu secukupnya- Air secukupnyaCara membuat:1. Tumis bumbu halus, serai, dan daun jeruk, masak sampai harum.2. Masukkan ayam suwir, aduk rata.3. Tambah sedikit air dan santan, aduk rata.4. Masak sampai air berkurang, tambahkan saus tiram, aduk rata.5. Tambahkan gula, garam, dan kaldu jamur. Cek rasa.6. Terakhir masukkan daun kemangi, aduk rata, masak sebentar. Siap disajikan" },
  { title: "Pepes Ayam", link: "31723032.html", description: "Bahan:- 1 kg daging ayam potong- 3 lembar daun salam- 2 batang serai, potong kasar dan memarkan- Daun kemangi secukupnya- Gula dan garam secukupnya- 2 sdm minyak goreng- 1 tangkai bawang daun, iris halus- Daun pisang secukupnyaBumbu marinasi:- 5 cm jahe dihaluskan- 5 cm kunyit dihaluskan- GaramBumbu halus:- 6 kemiri sangrai- 4 siung bawang putih- 7 siung bawang merah- 2 ruas jari kunyit- 5 cm jahe- 1 sdt merica- 1/2 sdt ketumbar sangrai- GaramCara membuat:1. Cuci daging ayam sampai bersih, lalu lumuri dengan bumbu marinasi. Diamkan sesaat.2. Panaskan minyak goreng, tumis bumbu halus sebentar saja,angkat bumbu lalu campurkan bumbu dengan daging ayam dan bahan lainnya, aduk rata.3. Siapkan daun pisang, bungkus pepes dengan rapi. Kemudian kukus selama 1 jam. Setelah pepes matang, bakar sebentar saja. Sajikan." },
  { title: "Ayam Goreng Batam", link: "312390182.html", description: "Bahan:- 1 ekor ayam, potong beberapa bagian- 1 sdm ketumbar bubuk- 2 sdt garam- 1 butir telur- 50 gr tepung maizena atau tapioka- Lada dan kaldu bubuk sesuai selera- Minyak untuk menggorengBumbu halus:- 7 siung bawang putih- 2 siung bawang merah- 2 cm jahe- 2 cm kunyit- Air secukupnyaCara membuat:1. Campur semua bahan dan bumbu halus, aduk rata. Marinasi minimal selama 1 jam atau semalaman di freezer.2. Goreng hingga kecokelatan dengan api kecil sedang." },
  { title: "Chicken Pok Pok", link: "31029181.html", description: "Bahan:- 350 gr dada ayam fillet- 1 butir telur ayam- 2 sdm tepung maizena- 1 sdm krimer bubuk- Tepung serbaguna secukupnyaBumbu marinasi:- 4 siung bawang putih, parut- 1/2 sdt lada bubuk- 1 sdt garam- 1/2 sdt penyedap jamur- 3 sdm air jeruk kunciCara membuat:1. Potong dadu dada ayam, lalu marinasi dengan bumbu sampai meresap.2. Campur tepung maizena dan krimer, lalu balur merata ke potongan ayam.3. Kocok merata telur lalu tuang ke dalam potongan ayam tepung tadi, balur merata.4. Tuang tepung serbaguna ke dalam wadah, balur merata ke potongan ayam sambil sedikit diremas, lakukan sampai habis.5. Panaskan minyak goreng, lalu goreng sampai golden brown, angkat dan tiriskan.6. Sajikan dengan sambal." },
];

const mappingDiv = document.getElementById("mapping");
let content = "";

for (let i = 0; i < data.length; i++) {
  content +=  
    '<div class="content-menu" role="button">' +
    '<a href= "'+data[i].link+'">' +
    '<img className="menu-img" src="../src/img/'+data[i].title+'.webp" />' +
    '<div class="details-menu">' +
    '<h3 className="menu-title">' +
    data[i].title +
    "</h3>" +
    '<p className="menu-description">' +
    data[i].description +
    "</p>" +
    "</div>" +
    "</a>" +
    "</div>";
}

mappingDiv.innerHTML = content;

